version: '3.9'
services:

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"

  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "${FASTAPI_PORT}:8000"
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
    env_file:
      - .env

  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
    ports:
      - "5050:5050"
    volumes:
      - ${PWD}/allure-results:/app/allure-results
      - ${PWD}/allure-reports:/app/default-reports
